/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaInventario;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import conexionBaseDeDatos.Conexion;
import controladorInventario.EliminarProducto;
import controladorInventario.ModificarProducto;
import controladorInventario.MostrarProducto;
import java.awt.Image;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modeloInventario.Bebidas;
import modeloInventario.Comida;
import modeloInventario.Producto;

public class Inventario extends javax.swing.JFrame {
    ModificarProducto modify = new ModificarProducto();
    MostrarProducto wach = new MostrarProducto();
    EliminarProducto delet = new EliminarProducto();

    public Inventario() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagen/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        modificarBottomPag = new javax.swing.JButton();
        mostratPagBottom = new javax.swing.JButton();
        agregarPagBottom = new javax.swing.JButton();
        pagInicioBottom = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanem = new javax.swing.JTabbedPane();
        pagInicio = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        añadirProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        precioProducto = new javax.swing.JTextField();
        cantidadProducto = new javax.swing.JTextField();
        imagenProducto = new javax.swing.JTextField();
        categoriaBox = new javax.swing.JComboBox<>();
        agregarProducto = new javax.swing.JButton();
        limpiarBotones = new javax.swing.JButton();
        modificarProducto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        modificarT = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        saveP = new javax.swing.JButton();
        nombreP = new javax.swing.JTextField();
        precioP = new javax.swing.JTextField();
        Clase2 = new javax.swing.JComboBox<>();
        cantidadP = new javax.swing.JTextField();
        idP = new javax.swing.JTextField();
        claseP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mostrarProducto = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        recargar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        eliminar1 = new javax.swing.JButton();
        mostrarBotom1 = new javax.swing.JButton();
        Clase = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 0, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(850, 75));

        modificarBottomPag.setBackground(new java.awt.Color(255, 204, 0));
        modificarBottomPag.setText("Modificar");
        modificarBottomPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBottomPagActionPerformed(evt);
            }
        });

        mostratPagBottom.setBackground(new java.awt.Color(255, 204, 0));
        mostratPagBottom.setText("Mostrar");
        mostratPagBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostratPagBottomActionPerformed(evt);
            }
        });

        agregarPagBottom.setBackground(new java.awt.Color(255, 204, 0));
        agregarPagBottom.setText("Agregar");
        agregarPagBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPagBottomActionPerformed(evt);
            }
        });

        pagInicioBottom.setBackground(new java.awt.Color(255, 204, 0));
        pagInicioBottom.setText("Inicio");
        pagInicioBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagInicioBottomActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pagInicioBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(mostratPagBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregarPagBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificarBottomPag, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modificarBottomPag, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(agregarPagBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mostratPagBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pagInicioBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jPanem.setToolTipText("");
        jPanem.setEnabled(false);
        jPanem.setFocusable(false);
        jPanem.setMaximumSize(new java.awt.Dimension(1026, 784));
        jPanem.setRequestFocusEnabled(false);
        jPanem.setVerifyInputWhenFocusTarget(false);

        pagInicio.setDoubleBuffered(false);
        pagInicio.setEnabled(false);
        pagInicio.setFocusable(false);
        pagInicio.setOpaque(false);
        pagInicio.setRequestFocusEnabled(false);
        pagInicio.setVerifyInputWhenFocusTarget(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 255));
        jLabel13.setText("Bienvenido  a ");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Duoc");

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Inventario ");

        jLabel14.setBackground(new java.awt.Color(255, 255, 0));
        jLabel14.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("UC");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 366, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pagInicioLayout = new javax.swing.GroupLayout(pagInicio);
        pagInicio.setLayout(pagInicioLayout);
        pagInicioLayout.setHorizontalGroup(
            pagInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagInicioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pagInicioLayout.setVerticalGroup(
            pagInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanem.addTab("tab4", pagInicio);

        añadirProducto.setBackground(new java.awt.Color(255, 204, 0));

        jLabel2.setText("Ingrese la categoría del producto");

        jLabel3.setText("Ingrese el nombre del producto");

        jLabel4.setText("Ingrese el precio del producto");

        jLabel5.setText("Ingrese la cantidad del producto");

        jLabel6.setText("Ingrese la imagen del producto");

        nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoActionPerformed(evt);
            }
        });

        precioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioProductoActionPerformed(evt);
            }
        });

        cantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadProductoActionPerformed(evt);
            }
        });

        imagenProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenProductoActionPerformed(evt);
            }
        });

        categoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Comida" }));
        categoriaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaBoxActionPerformed(evt);
            }
        });

        agregarProducto.setText("Agregar");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });

        limpiarBotones.setText("Limpiar");
        limpiarBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBotonesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout añadirProductoLayout = new javax.swing.GroupLayout(añadirProducto);
        añadirProducto.setLayout(añadirProductoLayout);
        añadirProductoLayout.setHorizontalGroup(
            añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirProductoLayout.createSequentialGroup()
                .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(añadirProductoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cantidadProducto)
                                .addComponent(imagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(añadirProductoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(añadirProductoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(limpiarBotones)
                        .addGap(182, 182, 182)
                        .addComponent(agregarProducto)))
                .addContainerGap(687, Short.MAX_VALUE))
        );
        añadirProductoLayout.setVerticalGroup(
            añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirProductoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(añadirProductoLayout.createSequentialGroup()
                        .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(añadirProductoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGroup(añadirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(añadirProductoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(limpiarBotones))
                    .addGroup(añadirProductoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(agregarProducto)))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jPanem.addTab("Agregar", añadirProducto);

        modificarProducto.setBackground(new java.awt.Color(255, 204, 0));

        modificarT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRE", "PRECIO", "CANTIDAD", "CLASE"
            }
        ));
        modificarT.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                modificarTAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        modificarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(modificarT);

        jLabel12.setText("Clase:");

        saveP.setText("Guardar");
        saveP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePActionPerformed(evt);
            }
        });

        Clase2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item no selcionar", "Bebida", "Comida" }));

        cantidadP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadPActionPerformed(evt);
            }
        });

        idP.setEditable(false);
        idP.setAutoscrolls(false);
        idP.setEnabled(false);
        idP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPActionPerformed(evt);
            }
        });

        claseP.setEditable(false);
        claseP.setEnabled(false);
        claseP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasePActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre:");

        jLabel9.setText("Cantidad:");

        jLabel10.setText("Precio:");

        jLabel11.setText("ID:");

        javax.swing.GroupLayout modificarProductoLayout = new javax.swing.GroupLayout(modificarProducto);
        modificarProducto.setLayout(modificarProductoLayout);
        modificarProductoLayout.setHorizontalGroup(
            modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarProductoLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(saveP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarProductoLayout.createSequentialGroup()
                        .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarProductoLayout.createSequentialGroup()
                                .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreP, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(precioP)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarProductoLayout.createSequentialGroup()
                                .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(claseP)
                                    .addComponent(cantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarProductoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(idP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        modificarProductoLayout.setVerticalGroup(
            modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductoLayout.createSequentialGroup()
                .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarProductoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(claseP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(Clase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(saveP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarProductoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jPanem.addTab("Cambiar", modificarProducto);

        mostrarProducto.setBackground(new java.awt.Color(255, 204, 0));

        jButton3.setText("Limpiar");

        recargar1.setText("Recargar");
        recargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargar1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idProducto", "nombre", "precio", "Title 4"
            }
        ));
        jTable2.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTable2HierarchyChanged(evt);
            }
        });
        jTable2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jLabel7.setText("ID PRODUCTO");

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });

        eliminar1.setText("Eliminar");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });

        mostrarBotom1.setText("Mostrar");
        mostrarBotom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBotom1ActionPerformed(evt);
            }
        });

        Clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item no selcionar", "Bebida", "Comida" }));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/qiyana.png"))); // NOI18N

        javax.swing.GroupLayout mostrarProductoLayout = new javax.swing.GroupLayout(mostrarProducto);
        mostrarProducto.setLayout(mostrarProductoLayout);
        mostrarProductoLayout.setHorizontalGroup(
            mostrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarProductoLayout.createSequentialGroup()
                .addGroup(mostrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrarProductoLayout.createSequentialGroup()
                        .addGroup(mostrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mostrarProductoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mostrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mostrarProductoLayout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eliminar1)
                                        .addGap(206, 206, 206)
                                        .addComponent(recargar1)
                                        .addGap(76, 76, 76)
                                        .addComponent(mostrarBotom1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mostrarProductoLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(mostrarProductoLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 421, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrarProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addContainerGap())
        );
        mostrarProductoLayout.setVerticalGroup(
            mostrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarProductoLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(mostrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(mostrarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(recargar1)
                    .addComponent(eliminar1)
                    .addComponent(mostrarBotom1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanem.addTab("Mostrar", mostrarProducto);

        jPanel1.add(jPanem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 1080, 600));
        jPanem.getAccessibleContext().setAccessibleParent(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoActionPerformed

    }//GEN-LAST:event_nombreProductoActionPerformed

    private void precioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioProductoActionPerformed

    private void cantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadProductoActionPerformed

    private void imagenProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagenProductoActionPerformed

    private void categoriaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaBoxActionPerformed

    }//GEN-LAST:event_categoriaBoxActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        Producto nProductoC = new Comida();
        Producto nProductoB = new Bebidas();
        String categoria = categoriaBox.getSelectedItem().toString();
        String nombre = nombreProducto.getText().toUpperCase();

        int precio = Integer.parseInt(precioProducto.getText());
        int cantidad = Integer.parseInt(cantidadProducto.getText());

        if (categoria.equals("Bebida")) {

            nProductoB.NuevoProducto(nombre, precio, cantidad);

        } else if (categoria.equals("Comida")) {
            nProductoC.NuevoProducto(nombre, precio, cantidad);
        }

        if (!categoria.equals("") && !nombre.equals("") && !precioProducto.getText().equals("") && !cantidadProducto.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "El elemento a sido agregado exitosamente");

        } else {
            JOptionPane.showMessageDialog(null, "El elemento a sido agregado exitosamente");
        }

    }//GEN-LAST:event_agregarProductoActionPerformed

    private void limpiarBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBotonesActionPerformed
        nombreProducto.setText("");
        precioProducto.setText("");
        cantidadProducto.setText("");

    }//GEN-LAST:event_limpiarBotonesActionPerformed

    private void recargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargar1ActionPerformed

    }//GEN-LAST:event_recargar1ActionPerformed

    private void jTable2HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTable2HierarchyChanged

    }//GEN-LAST:event_jTable2HierarchyChanged

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        int idInt = Integer.parseInt(idtxt.getText());
        delet.EliminarProducto(idInt);
        JOptionPane.showMessageDialog(null, "EL elemento a sido eliminado correctamente");
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void mostrarBotom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBotom1ActionPerformed
        String idt = idtxt.getText();
        String cat = this.Clase.getSelectedItem().toString();
        wach.mostrar(jTable2, idt, cat);
    }//GEN-LAST:event_mostrarBotom1ActionPerformed

    private void modificarTAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_modificarTAncestorAdded
        modify.TablaModificar(modificarT);
    }//GEN-LAST:event_modificarTAncestorAdded

    private void modificarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarTMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion conn = new Conexion();
            Connection con = conn.conexionBD();

            int fila = modificarT.getSelectedRow();
            String idproducto = modificarT.getValueAt(fila, 0).toString();

            ps = con.prepareStatement("SELECT idproducto,nombre,precio,cantidad,clase FROM producto.producto WHERE idproducto=?");

            ps.setString(1, idproducto);

            rs = ps.executeQuery();

            while (rs.next()) {
                idP.setText(rs.getString("idproducto"));
                nombreP.setText(rs.getString("nombre"));
                precioP.setText(rs.getString("precio"));
                cantidadP.setText(rs.getString("cantidad"));
                claseP.setText(rs.getString("clase"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_modificarTMouseClicked

    private void savePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePActionPerformed
        if (!this.idP.getText().equals("")) {
            int idproducto = Integer.parseInt(idP.getText());
            String nombreProducto = nombreP.getText().toUpperCase();
            int precioProducto = Integer.parseInt(precioP.getText());
            int cantidadProducto = Integer.parseInt(cantidadP.getText());
            String clase = this.Clase2.getSelectedItem().toString();

            if (clase.equals("Comida")) {
                modify.ModificarBD(idproducto, nombreProducto, precioProducto, cantidadProducto, "C");
                JOptionPane.showMessageDialog(null, "Se a modificado correctamente");
            } else if (clase.equals("Bebida")) {

                modify.ModificarBD(idproducto, nombreProducto, precioProducto, cantidadProducto, "B");
                JOptionPane.showMessageDialog(null, "Se a modificado correctamente");

            } else {
                JOptionPane.showMessageDialog(null, "No se a modificado correctamente\n revice los datos");

            }
        }
        modify.TablaModificar(this.modificarT);
    }//GEN-LAST:event_savePActionPerformed

    private void cantidadPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadPActionPerformed

    private void clasePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasePActionPerformed

    }//GEN-LAST:event_clasePActionPerformed

    private void jTable2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable2AncestorAdded
        String idt = idtxt.getText();
        String cat = this.Clase.getSelectedItem().toString();
        wach.mostrar(jTable2, idt, cat);
    }//GEN-LAST:event_jTable2AncestorAdded

    private void idPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPActionPerformed

    private void pagInicioBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagInicioBottomActionPerformed
        this.jPanem.setSelectedIndex(0);
    }//GEN-LAST:event_pagInicioBottomActionPerformed

    private void modificarBottomPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBottomPagActionPerformed
        this.jPanem.setSelectedIndex(3);
    }//GEN-LAST:event_modificarBottomPagActionPerformed

    private void mostratPagBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostratPagBottomActionPerformed
        jPanem.setSelectedIndex(1);
        String idt = idtxt.getText();
        String cat = this.Clase.getSelectedItem().toString();
        wach.mostrar(jTable2, idt, cat);
        this.jPanem.setSelectedIndex(2);
    }//GEN-LAST:event_mostratPagBottomActionPerformed

    private void agregarPagBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPagBottomActionPerformed
        this.jPanem.setSelectedIndex(1);
    }//GEN-LAST:event_agregarPagBottomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Clase;
    private javax.swing.JComboBox<String> Clase2;
    private javax.swing.JButton agregarPagBottom;
    private javax.swing.JButton agregarProducto;
    private javax.swing.JPanel añadirProducto;
    private javax.swing.JTextField cantidadP;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JComboBox<String> categoriaBox;
    private javax.swing.JTextField claseP;
    private javax.swing.JButton eliminar1;
    private javax.swing.JTextField idP;
    private javax.swing.JTextField idtxt;
    private javax.swing.JTextField imagenProducto;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jPanem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton limpiarBotones;
    private javax.swing.JButton modificarBottomPag;
    private javax.swing.JPanel modificarProducto;
    private javax.swing.JTable modificarT;
    private javax.swing.JButton mostrarBotom1;
    private javax.swing.JPanel mostrarProducto;
    private javax.swing.JButton mostratPagBottom;
    private javax.swing.JTextField nombreP;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JPanel pagInicio;
    private javax.swing.JButton pagInicioBottom;
    private javax.swing.JTextField precioP;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JButton recargar1;
    private javax.swing.JButton saveP;
    // End of variables declaration//GEN-END:variables
}
